<a href="https://colab.research.google.com/github/pavlovid107b21/lambda/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Библиотека Numpy

---

При работе с предыдущими ноутбуками вы познакомились с основами языка Python. Узнали, что Python -- довольно простой, понятный язык программирования, научились пользоваться jupyter notebook'ом и оценили плюсы и возможности python+jupyter -- написание кода в отдельных ячейках и последовательный запуск кода в ячейках.

Но есть и обратная сторона медали -- Python очень медленный язык. Возможно, пока что это было не очень заметно, потому что мы не работали с большими массивами данных. Но в эпоху big data, при работе с огромными массивами данных даже небольшое отставание языка программирования по скорости становится заметно и критично. Есть, конечно, языки программирования, которые работают намного быстрее (например, С++), но они гораздо сложнее в написании и не интерпретируемы, а компилируемы (то есть, в jupyter notebook'е с такими языками работать бы не получилось). 

Как же найти компромисс? Ответ прост: написать python-библиотеку для работы с массивами данных, функции которой будут написаны на очень быстром языке С++, но которую можно было бы использовать из Python. Эта библиотека называется **NumPy** (НамПай).

Пакет `numpy` предоставляет интерфейс для работы с $n$-мерными массивами. В `numpy` реализовано множество всевозможных операций над массивами в целом. Если задачу можно решить, произведя некоторую последовательность операций над массивами, то с помощью numpy в python это будет столь же эффективно, как в `C` или `matlab`.

Конечно, тот факт, что код numpy написан на С++, накладывает некоторые ограничения на массивы этой библиотеки: в любом numpy-массиве могут храниться элементы только одного типа: например, все float или все string (как вы помните с прошлого урока, в обычном pythonв массивах могут быть элементы совершенно разных типов)

Этот ноутбук полностью посвещен знакомству с библиотекой numpy и работе с ней

## Одномерные массивы

### Создание массива 

In [ ]:
# принято, что numpy импортируют именно так
import numpy as np

Как же завести массив в numpy?

Очень просто! Надо всего лишь перевести обычный python list в np.array:

In [ ]:
# 'перевести' python list в np.array -- это обернуть массив в np.array()
a = np.array([3, 4, 1])
print(a)
type(a)

[3 4 1]


numpy.ndarray

Обычный питоновский `print` печатает массивы в удобной форме (точно так же, как и list питона)

In [ ]:
print(a)

[3 4 1]


### Типы данных в массивах np.array

Поговорим о типах данных, хранящихся в массивах:

Чаще всего мы будем работать с числовыми массивами, поэтому поговорим о инх.

В отличие от чистого питона, в `numpy` есть несколько типов для целых чисел (`int16`, `int32`, `int64`) и чисел с плавающей точкой (`float32`, `float64`). Они отличаются тем, с какой точностью в памяти хранятся элементы массива. 

Чтобы посмотреть, какой тип у вашего массива, можно вывести его dtype:

In [ ]:
a.dtype

dtype('int64')

Конечно, можно скастовать массив из одного типа в другой. 

Давайте переведем наш массив 'a' из типа np.int64 в тип np.float32:

In [ ]:
a = a.astype(np.float32)
a.dtype

dtype('float32')

Далее мы будем рассматривать n-мерный массивы, для них преобразование типов работает так же. И для них все еще все элементы должны иметь одинаковый тип.

### Изменение массивов np.array

Как и list в питоне, массивы np.array - изменяемые объекты. Механика изменений значений в них такая же, как у питоновских list'ов. Давайте в этом убедимся:

In [ ]:
a = np.array([3, 4 ,1])

a[1] = 3
print(a)

[3 3 1]


Единственный (но логичный) нюанс: при изменении значения в массиве с элементами одного типа на элемент другого типа новый элемент будет приведен к типу массива:

In [ ]:
# или: a = np.array([3, 4 ,1], dtype=np.int64)
a = np.array([3, 4 ,1]).astype(np.int64)

# значение 3.5 будет приведено к типу int64, т.е. станет 3
a[1] = 3.5
print(a)

[3 3 1]


In [ ]:
# обратите внимание -- если создается np.array с чисоами разных типов (int и float), 
# то все числа будут приведены к более точному типу, т.е. float
# таким образом, 1 из целого числа станет числом с плавающей точкой 1.
a = np.array([3., 4. ,1])

# значение 5 будет приведено к типу int64, т.е. станет 5.
a[1] = 5
print(a)

[3. 5. 1.]


А вот добавить к массиву новый элемент в конец чуть сложнее, чем у list. Напримним, в list это делалось с помощью метода .append(). В numpy это также делается с помощью append, но чуть по-другому:

Обратите внимание, что в numpy при append *создается новый массив*, а не происходит добавление элемента в уже существующий массив. Поэтому не рекомендуется создавать массивы с помощью append в numpy.

In [ ]:
a = np.array([3, 4 ,1])

# вот так пишется append
a = np.append(a, 6)

a

array([3, 4, 1, 6])

## Многомерные массивы

Мы узнали, как создавать и изменять одномерные массивы, как они выглядят в numpy и нюансы приведения типов. Настало время познакомиться с многомерными массивами.

Многомерный массив -- это массив, элементы которого тоже массивы. В принципе, ничего нового, все как и у list в питоне. 

In [ ]:
two_dim_array = np.array([[2, 3], [4, 5]])

print(two_dim_array)

[[2 3]
 [4 5]]


In [ ]:
two_dim_array[0][0]

2

In [ ]:
three_dim_array = np.array([[[2, 3], [4, 5]], [[5, 6], [7, 8]]])

print(three_dim_array)

[[[2 3]
  [4 5]]

 [[5 6]
  [7 8]]]


Напомним, что в numpy, неважно, в одномерном или многомерном массиве, *все* элементы имеют одинаковый тип

Давайте в этом убедимся:

In [ ]:
# 2 и 3 приведутся к типу чисел 4. и 5., т.е. float64
a = np.array([[2, 3], [4., 5.]])
print(a, a.dtype)



[[2. 3.]
 [4. 5.]] float64


### Информация о массиве

In [ ]:
Теперь научимся получать основную информацию о массиве

## Операции над одномерными массивами


 ### Арифметические операции

In [ ]:
a = np.array([2, 5, 6, 7])
b = np.array([9, 7, 8, 9])

С двумя массивами одинаковой 

In [ ]:
print(a + b)

[11 12 14 16]


In [ ]:
print(a - b)

[-7 -2 -2 -2]


In [ ]:
print(a * b)

[18 35 48 63]


In [ ]:
print(a / b)

[0.22222222 0.71428571 0.75       0.77777778]


In [ ]:
print(a ** 2)

[ 4 25 36 49]


`numpy` содержит элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (`ufunc`).

In [ ]:
np.sin, type(np.sin)

(<ufunc 'sin'>, numpy.ufunc)

In [ ]:
print(np.sin(a))
print(np.cosh(a))

[ 0.90929743 -0.95892427 -0.2794155   0.6569866 ]
[  3.76219569  74.20994852 201.71563612 548.31703516]


In [ ]:
np.exp(2)

7.38905609893065

Один из операндов может быть скаляром, а не массивом.

In [ ]:
a

array([2, 5, 6, 7])

In [ ]:
print(a + 1)

[3 6 7 8]


In [ ]:
print(2 * a)

[ 4 10 12 14]


Сравнения дают булевы массивы.

In [ ]:
print(a > b)

[False False False False]


In [ ]:
print(a < b)

[ True  True  True  True]


In [ ]:
print(a == b)

[False False False False]


In [ ]:
c = a > 5
print(c)

[False False  True  True]


Кванторы "существует" и "для всех".

In [ ]:
np.any(c), np.all(c)

(True, False)

Модификация на месте.

In [ ]:
a += 1
print(a)

[3 6 7 8]


In [ ]:
b *= 2
print(b)

[18 14 16 18]


In [ ]:
b /= a
print(b)

[ 0.          3.90243902  7.61904762 11.1627907  14.54545455]


При выполнении операций над массивами деление на 0 не возбуждает исключения, а даёт значения `np.nan` или `np.inf`.

In [ ]:
np.nan + 1, np.inf + 1, np.inf * 0, 1. / np.inf

(nan, inf, nan, 0.0)

Сумма и произведение всех элементов массива; максимальный и минимальный элемент; среднее и среднеквадратичное отклонение.

In [ ]:
b.sum(), b.prod(), b.max(), b.min(), b.mean(), b.std()

(33, 4536, 9, 7, 8.25, 0.82915619758885)

In [ ]:
x = np.random.normal(size=1000)
x.mean(), x.std()

(0.03896252357638703, 1.000200029613634)

In [ ]:
x

array([-2.37638460e-01, -2.41685439e-01,  2.05724428e-01,  5.01005739e-01,
        1.42005080e+00,  2.45062731e-01,  1.03842948e+00,  1.66320998e+00,
       -4.32409810e-01,  1.40359034e+00,  5.01054759e-01, -1.11948035e+00,
        4.97280364e-02, -3.61861823e-01, -1.01226999e+00, -1.56905706e+00,
       -9.14388508e-01,  9.04496224e-01, -3.24296335e-01, -6.54300347e-01,
        8.35776120e-01,  5.65565978e-01,  8.56758361e-01,  8.35109180e-01,
        1.11606381e+00, -1.31660901e-01, -2.83593902e-03,  1.08126202e+00,
        1.35788318e+00,  3.10117362e-01, -2.19703920e+00,  1.44318512e+00,
        9.14409974e-01,  6.33977517e-01,  1.58491277e+00, -9.85278521e-01,
       -1.05214284e+00, -9.12994626e-01,  3.14624074e-01,  2.06933346e+00,
        3.35972830e-01, -5.24990933e-01, -1.26933669e+00,  1.30782600e+00,
       -2.10363555e+00,  1.48007843e-01, -1.00691657e-01, -3.27514617e-01,
        2.44495587e-01,  6.31848645e-01,  1.01363916e+00,  6.28906106e-01,
        2.27586522e-01,  

Имеются встроенные функции

In [ ]:
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b + 1))
print(np.sin(b))
print(np.e, np.pi)

[0.         1.97545919 2.76026224 3.34107628 3.81385036]
[1.00000000e+00 4.95230899e+01 2.03662157e+03 7.04593127e+04
 2.07496438e+06]
[0.         1.58973284 2.15397459 2.49838135 2.74376828]
[ 0.         -0.68953468  0.9725297  -0.98605188  0.91780205]
2.718281828459045 3.141592653589793


Иногда бывает нужно использовать частичные (кумулятивные) суммы. В нашем курсе такое пригодится.

In [ ]:
b

array([18, 14, 16, 18])

In [ ]:
print(b.cumsum()[::-1])

[66 48 32 18]


Функция `sort` возвращает отсортированную копию, метод `sort` сортирует на месте.

In [ ]:
print(np.sort(b))
print(b)

[14 16 18 18]
[18 14 16 18]


In [ ]:
b.sort()
print(b)

[14 16 18 18]


Объединение массивов "по-горизонтали" (horizontal stack).

In [ ]:
a = np.array([1, 2, 3])
b = np.array([100, 200, 300])

print(np.hstack((a, b)))

[  1   2   3 100 200 300]


Объединение массивов "по-вертикали" (vertical stack).

In [ ]:
print(np.vstack((a, b)))

[[  1   2   3]
 [100 200 300]]


Расщепление массива в позициях 3 и 6.

In [ ]:
a = np.random.random(10)
np.hsplit(a, [3, 6])

[array([0.64501372, 0.99102171, 0.28545633]),
 array([0.6489831 , 0.95678594, 0.80428645]),
 array([0.59815893, 0.81674245, 0.44190248, 0.47429843])]

Функции `delete`, `insert` и `append` не меняют массив на месте, а возвращают новый массив, в котором удалены, вставлены в середину или добавлены в конец какие-то элементы.

In [ ]:
a = np.arange(0.1, 0.9, 0.001)
a

array([0.1  , 0.101, 0.102, 0.103, 0.104, 0.105, 0.106, 0.107, 0.108,
       0.109, 0.11 , 0.111, 0.112, 0.113, 0.114, 0.115, 0.116, 0.117,
       0.118, 0.119, 0.12 , 0.121, 0.122, 0.123, 0.124, 0.125, 0.126,
       0.127, 0.128, 0.129, 0.13 , 0.131, 0.132, 0.133, 0.134, 0.135,
       0.136, 0.137, 0.138, 0.139, 0.14 , 0.141, 0.142, 0.143, 0.144,
       0.145, 0.146, 0.147, 0.148, 0.149, 0.15 , 0.151, 0.152, 0.153,
       0.154, 0.155, 0.156, 0.157, 0.158, 0.159, 0.16 , 0.161, 0.162,
       0.163, 0.164, 0.165, 0.166, 0.167, 0.168, 0.169, 0.17 , 0.171,
       0.172, 0.173, 0.174, 0.175, 0.176, 0.177, 0.178, 0.179, 0.18 ,
       0.181, 0.182, 0.183, 0.184, 0.185, 0.186, 0.187, 0.188, 0.189,
       0.19 , 0.191, 0.192, 0.193, 0.194, 0.195, 0.196, 0.197, 0.198,
       0.199, 0.2  , 0.201, 0.202, 0.203, 0.204, 0.205, 0.206, 0.207,
       0.208, 0.209, 0.21 , 0.211, 0.212, 0.213, 0.214, 0.215, 0.216,
       0.217, 0.218, 0.219, 0.22 , 0.221, 0.222, 0.223, 0.224, 0.225,
       0.226, 0.227,

In [ ]:
a

array([0.1  , 0.101, 0.102, 0.103, 0.104, 0.105, 0.106, 0.107, 0.108,
       0.109, 0.11 , 0.111, 0.112, 0.113, 0.114, 0.115, 0.116, 0.117,
       0.118, 0.119, 0.12 , 0.121, 0.122, 0.123, 0.124, 0.125, 0.126,
       0.127, 0.128, 0.129, 0.13 , 0.131, 0.132, 0.133, 0.134, 0.135,
       0.136, 0.137, 0.138, 0.139, 0.14 , 0.141, 0.142, 0.143, 0.144,
       0.145, 0.146, 0.147, 0.148, 0.149, 0.15 , 0.151, 0.152, 0.153,
       0.154, 0.155, 0.156, 0.157, 0.158, 0.159, 0.16 , 0.161, 0.162,
       0.163, 0.164, 0.165, 0.166, 0.167, 0.168, 0.169, 0.17 , 0.171,
       0.172, 0.173, 0.174, 0.175, 0.176, 0.177, 0.178, 0.179, 0.18 ,
       0.181, 0.182, 0.183, 0.184, 0.185, 0.186, 0.187, 0.188, 0.189,
       0.19 , 0.191, 0.192, 0.193, 0.194, 0.195, 0.196, 0.197, 0.198,
       0.199, 0.2  , 0.201, 0.202, 0.203, 0.204, 0.205, 0.206, 0.207,
       0.208, 0.209, 0.21 , 0.211, 0.212, 0.213, 0.214, 0.215, 0.216,
       0.217, 0.218, 0.219, 0.22 , 0.221, 0.222, 0.223, 0.224, 0.225,
       0.226, 0.227,

In [ ]:
a = np.delete(a, [5, 7])
print(a)

[0 1 2 3 4 6 8 9]


In [ ]:
a = np.insert(a, 2, [0, 0])
print(a)

[0 1 0 0 2 3 4 6 8 9]


In [ ]:
a = np.append(a, [1, 2, 3])
print(a)

[0 1 0 0 2 3 4 6 8 9 1 2 3]


Есть несколько способов индексации массива. Вот обычный индекс.

In [ ]:
a = np.linspace(0, 1, 11)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
b = a[2]
print(b)

0.2


Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.

In [ ]:
b = a[2:6]
print(b)

[0.2 0.3 0.4 0.5]


In [ ]:
b[0] = -0.2
print(b)

[-0.2  0.3  0.4  0.5]


In [ ]:
print(a)

[ 0.   0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Диапазон с шагом 2.

In [ ]:
b = a[1:10:2]
print(b)

[0.1 0.3 0.5 0.7 0.9]


In [ ]:
b[0] = -0.1
print(a)

[ 0.  -0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Массив в обратном порядке.

In [ ]:
b = a[len(a):0:-1]
print(b)

[ 1.   0.9  0.8  0.7  0.6  0.5  0.4  0.3 -0.2 -0.1]


Подмассиву можно присвоить значение - массив правильного размера или скаляр.

In [ ]:
a[1:10:3] = 0
print(a)

[ 0.   0.  -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Тут опять создаётся только новый заголовок, указывающий на те же данные.

In [ ]:
b = a[:]
b[1] = 0.1
print(a)

[ 0.   0.1 -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Чтобы скопировать и данные массива, нужно использовать метод `copy`.

In [ ]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

In [ ]:
b[0] = -1

In [ ]:
a

array([-1,  2,  3])

In [ ]:
b = a.copy()
b[2] = 0
print(b)
print(a)

[-1  2  0]
[-1  2  3]


Можно задать список индексов.

In [ ]:
print(a[[2, 3, 5]])

[-0.2  0.3  0.5]


Можно задать булев массив той же величины.

In [ ]:
b = a > 0
print(b)

[False  True False  True False  True  True False  True  True  True]


In [ ]:
print(a[b])

[0.1 0.3 0.5 0.6 0.8 0.9 1. ]


## 2-мерные массивы

In [ ]:
a = np.array([[0.0, 1.0], [-1.0, 0.0]])
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 2)

In [ ]:
len(a), a.size

(2, 4)

In [ ]:
a[1, 0]

-1.0

Атрибуту `shape` можно присвоить новое значение - кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.

In [ ]:
b = np.linspace(0, 3, 4)
print(b)

[0. 1. 2. 3.]


In [ ]:
b.shape

(4,)

In [ ]:
b.shape = 2, 2
print(b)

[[0. 1.]
 [2. 3.]]


Можно растянуть в одномерный массив

In [ ]:
print(b.ravel())

[0. 1. 2. 3.]


Арифметические операции поэлементные

In [ ]:
a

array([[ 0.,  1.],
       [-1.,  0.]])

In [ ]:
b = np.array([[3, 4], 
    [8, 6 ]])
print(b)

[[3 4]
 [8 6]]


In [ ]:
print(a + 1)
print(a * 2)
print(a + [0, 1])  # второе слагаемое дополняется до матрицы копированием строк
print(a + np.array([[0, 2]]).T)  # .T - транспонирование
print(a + b)

[[1. 2.]
 [0. 1.]]
[[ 0.  2.]
 [-2.  0.]]
[[ 0.  2.]
 [-1.  1.]]
[[0. 1.]
 [1. 2.]]
[[3. 5.]
 [7. 6.]]


Поэлементное и матричное (только в Python 3.5) умножение.

In [ ]:
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [ ]:
print(b)

[[3 4]
 [8 6]]


In [ ]:
print(a * b)

[[ 0.  4.]
 [-8.  0.]]


In [ ]:
print(a @ b)

[[ 8.  6.]
 [-3. -4.]]


In [ ]:
print(b @ a)

[[-4.  3.]
 [-6.  8.]]


Умножение матрицы на вектор.

In [ ]:
v = np.array([1, -1], dtype=np.float64)
print(b @ v)

[-1.  2.]


In [ ]:
print(v @ b)

[-5. -2.]


Если у вас Питон более ранней версии, то для работы с матрицами можно использовать класс `np.matrix`, в котором операция умножения реализуется как матричное умножение.

In [ ]:
np.matrix(a) * np.matrix(b)

matrix([[ 2.,  3.],
        [ 0., -1.]])

Внешнее произведение $a_{ij}=u_i v_j$

In [ ]:
u = np.linspace(1, 2, 2)
v = np.linspace(2, 4, 3)
print(u)
print(v)

[1. 2.]
[2. 3. 4.]


In [ ]:
a = np.outer(u, v)
print(a)

[[2. 3. 4.]
 [4. 6. 8.]]


Двумерные массивы, зависящие только от одного индекса: $x_{ij}=u_j$, $y_{ij}=v_i$

In [ ]:
x, y = np.meshgrid(u, v)
print(x)
print(y)

[[1. 2.]
 [1. 2.]
 [1. 2.]]
[[2. 2.]
 [3. 3.]
 [4. 4.]]


Единичная матрица.

In [ ]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Метод `reshape` делает то же самое, что присваивание атрибуту `shape`.

In [ ]:
print(I.reshape(16))

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [ ]:
print(I.reshape(8, 2))

[[1. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]]


Строка.

In [ ]:
print(I[2])

[0. 0. 1. 0.]


Цикл по строкам.

In [ ]:
for row in I:
    print(row)

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


Столбец.

In [ ]:
print(I[1, 1])

1.0


Подматрица.

In [ ]:
print(I[0:2, 1:3])

[[0. 0.]
 [1. 0.]]


Можно построить двумерный массив из функции.

In [ ]:
def f(i, j):
    print(i)
    print(j)
    return 10 * i + j

print(np.fromfunction(f, (4, 4), dtype=np.int64))

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


Транспонированная матрица.

In [ ]:
print(b.T)

[[0. 2.]
 [1. 3.]]


Соединение матриц по горизонтали и по вертикали.

In [ ]:
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[4, 5], [6, 7], [8, 9]])
print(a)
print(b)
print(c)

[[0 1]
 [2 3]]
[[4 5 6]
 [7 8 9]]
[[4 5]
 [6 7]
 [8 9]]


In [ ]:
print(np.hstack((a, b)))

[[0 1 4 5 6]
 [2 3 7 8 9]]


In [ ]:
print(np.vstack((a, c)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Сумма всех элементов; суммы столбцов; суммы строк.

In [ ]:
b

array([[3, 4],
       [8, 6]])

In [ ]:
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

21
[11 10]
[ 7 14]


Аналогично работают `prod`, `max`, `min` и т.д.

In [ ]:
print(b.max())
print(b.max(axis=0))
print(b.min(axis=1))

9
[7 8 9]
[4 7]


След - сумма диагональных элементов.

In [ ]:
np.trace(a)

3

## Многомерные массивы
опциональный материал

In [ ]:
X = np.arange(24).reshape(2, 3, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Суммирование (аналогично остальные операции)

In [ ]:
# суммируем только по нулевой оси, то есть для фиксированных j и k суммируем только элементы с индексами (*, j, k)
print(X.sum(axis=0))
# суммируем сразу по двум осям, то есть для фиксированной i суммируем только элементы с индексами (i, *, *)
print(X.sum(axis=(1, 2)))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[ 66 210]


## Линейная алгебра

In [ ]:
np.linalg.det(a)

-2.0

Обратная матрица.

In [ ]:
a1 = np.linalg.inv(a)
print(a1)

[[-1.5  0.5]
 [ 1.   0. ]]


In [ ]:
print(a @ a1)
print(a1 @ a)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


Решение линейной системы $au=v$.

In [ ]:
v = np.array([0, 1], dtype=np.float64)
print(a1 @ v)

[0.5 0. ]


In [ ]:
u = np.linalg.solve(a, v)
print(u)

[0.5 0. ]


Проверим.

In [ ]:
print(a @ u - v)

[0. 0.]


Собственные значения и собственные векторы: $a u_i = \lambda_i u_i$. `l` - одномерный массив собственных значений $\lambda_i$, столбцы матрицы $u$ - собственные векторы $u_i$.

In [ ]:
l, u = np.linalg.eig(a)
print(l)

[-0.56155281  3.56155281]


In [ ]:
print(u)

[[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


Проверим.

In [ ]:
for i in range(2):
    print(a @ u[:, i] - l[i] * u[:, i])

[0.00000000e+00 1.66533454e-16]
[ 0.0000000e+00 -4.4408921e-16]


Функция `diag` от одномерного массива строит диагональную матрицу; от квадратной матрицы - возвращает одномерный массив её диагональных элементов.

In [ ]:
L = np.diag(l)
print(L)
print(np.diag(L))

[[-0.56155281  0.        ]
 [ 0.          3.56155281]]
[-0.56155281  3.56155281]


Все уравнения $a u_i = \lambda_i u_i$ можно собрать в одно матричное уравнение $a u = u \Lambda$, где $\Lambda$ - диагональная матрица с собственными значениями $\lambda_i$ на диагонали.

In [ ]:
print(a @ u - u @ L)

[[0.00000000e+00 0.00000000e+00]
 [1.11022302e-16 0.00000000e+00]]


Поэтому $u^{-1} a u = \Lambda$.

In [ ]:
print(np.linalg.inv(u) @ a @ u)

[[-5.61552813e-01  1.47801400e-17]
 [-1.25939966e-16  3.56155281e+00]]


Найдём теперь левые собственные векторы $v_i a = \lambda_i v_i$ (собственные значения $\lambda_i$ те же самые).

In [ ]:
l, v = np.linalg.eig(a.T)
print(l)
print(v)

[-0.56155281  3.56155281]
[[-0.96276969 -0.48963374]
 [ 0.27032301 -0.87192821]]


Собственные векторы нормированы на 1.

In [ ]:
print(u.T @ u)
print(v.T @ v)

[[ 1.         -0.23570226]
 [-0.23570226  1.        ]]
[[1.         0.23570226]
 [0.23570226 1.        ]]


Левые и правые собственные векторы, соответствующие разным собственным значениям, ортогональны, потому что $v_i a u_j = \lambda_i v_i u_j = \lambda_j v_i u_j$.

In [ ]:
print(v.T @ u)

[[ 9.71825316e-01 -7.57355847e-18]
 [-4.34446700e-17  9.71825316e-01]]


# Интегрирование

In [ ]:
from scipy.integrate import quad, odeint
from scipy.special import erf

In [ ]:
def f(x):
    return np.exp(-x ** 2)

Адаптивное численное интегрирование (может быть до бесконечности). `err` - оценка ошибки.

In [ ]:
res, err = quad(f, 0, np.inf)
print(np.sqrt(np.pi) / 2, res, err)

0.8862269254527579 0.8862269254527579 7.101318390472462e-09


In [ ]:
res, err =  quad(f, 0, 1)
print(np.sqrt(np.pi) / 2 * erf(1), res, err)

0.7468241328124269 0.7468241328124271 8.291413475940725e-15


## Сохранение в файл и чтение из файла

In [ ]:
x = np.arange(0, 25, 0.5).reshape((5, 10))

# Сохраняем в файл example.txt данные x в формате с двумя точками после запятой и разделителем ';'
np.savetxt('example.txt', x, fmt='%.2f', delimiter=';')

Получится такой файл

In [ ]:
!cat example.txt

0.00;0.50;1.00;1.50;2.00;2.50;3.00;3.50;4.00;4.50
5.00;5.50;6.00;6.50;7.00;7.50;8.00;8.50;9.00;9.50
10.00;10.50;11.00;11.50;12.00;12.50;13.00;13.50;14.00;14.50
15.00;15.50;16.00;16.50;17.00;17.50;18.00;18.50;19.00;19.50
20.00;20.50;21.00;21.50;22.00;22.50;23.00;23.50;24.00;24.50
