<a href="https://colab.research.google.com/github/pavlovid107b21/lambda/blob/main/Pavlov_homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
n = int(input())
x = int(input())
v = np.zeros(n).astype(np.int64)
v[x] = 1
print(v)

5
3
[0 0 0 1 0]


In [2]:
import numpy as np
n = int(input())
m = int(input())
s = int(input())
v = np.arange(n,m,s).astype(np.int64)
print(v)

2
500
10
[  2  12  22  32  42  52  62  72  82  92 102 112 122 132 142 152 162 172
 182 192 202 212 222 232 242 252 262 272 282 292 302 312 322 332 342 352
 362 372 382 392 402 412 422 432 442 452 462 472 482 492]


In [ ]:
import numpy as np

a = np.random.randint(0,8,9)
a.shape = 3,3
print(a)

[[1 1 7]
 [5 5 0]
 [3 2 0]]


In [ ]:
import numpy as np
a = np.random.randint(-10,10,16)
a.shape = 4,4
b = np.max(a[0],axis=0)
c = np.min(a[1],axis=0)
d = np.average(a[2],axis=0)
e = np.sum(a[3],axis=0)
print(b,c,d,e)

-2 -8 4.25 10


In [ ]:
import numpy as np
a = 5*np.eye(5).astype(np.int64)
print(a)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


In [3]:
import numpy as np
x = np.random.randint(-10,11,(6,6,6)).astype(np.int64)
print(np.max(x))

10


In [17]:
import numpy as np
def f(a,b):
  if len(a[1]) == len(b.T[1]): 
    return np.dot(a,b).T.astype(np.int64)
  else:
    return 0
a = np.array(([4.0,92.0,6.0],[-15.0,6.0,10.0],[9.0,8.0,3.0]))
b = np.array(([14.0,7.0,7.0],[6.0,40.0,13.0],[65.0,3.0,7.0]))
print(f(a,b))

[[ 998  476  369]
 [3726  165  392]
 [1266   43  188]]


In [36]:
import numpy as np
def f(x1,x2):
  return x1**2 + 2*x2**2 + np.exp(x1 + x2)
x1 = np.random.randint(-1000,1000)
x2 = np.random.randint(-1000,1000)
e = 0.5
dydx1 = np.gradient(f, x1)
dydx2 = np.gradient(f, x2)
F = np.array([dydx1,dydx2])
while (abs(x1) >= e) and (abs(x2) >= e):
  x1 = x1 - e*F[0]
  x2 = x2 - e*F[1]
print(x1,x2)


[] []


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  # Remove the CWD from sys.path while we load stuff.
